class Path {
    constructor() {
        this.home = '/'
        this.auth = '/auth'
        this.login = '/login'
        this.register = '/register'
        this.forgotPassword = '/forgotPassword'
        this.profile = '/profile'
        this.healthtools = '/health-tools'
        this.bmi = '/health-tools/bmi'
        this.group = '/community'
        this.groupdetail = '/community/groupdetail'
        this.veirifyEmail = '/auth/verify-account'
        this.hearttool =  '/health-tools/hearttool'
        this.system = '/system'
        this.specialistManagement = '/system/specialistManagement'
        this.addSpecialist = '/system/addSpecialist'
        this.editSpecialist = '/system/editSpecialist/:id'
        this.clinicManagement = '/system/clinicManagement'
        this.addClinic = '/system/addClinic'
        this.updateClinic = '/system/updateClinic/:id'
        this.hospitalManagement = '/system/hospitalManagement'
        this.addHospital = '/system/addHospital'
        this.updateHospital = '/system/updateHospital/:id'
        this.patientManagement = '/system/patientManagement'
        this.doctorManagement = '/system/doctorManagement'
        this.addDoctor = '/system/addDoctor'
        this.updateDoctor = '/system/updateDoctor/:id'
        this.scheduleManagement = '/system/scheduleManagement'
        this.appointmentManagement = '/system/appointmentManagement'
        this.revenueManagement = '/system/revenueManagement'
    }
}

export const path = new Path()